name:                shah
version:             0.1.0.0
github:              "githubuser/mohsen3"
license:             BSD3
author:              "mohsen3"
copyright:           "2021 Mohsen Mollanoori"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/shah#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- karver
- text
- optparse-applicative
- optparse-simple
- bytestring
- yaml
- process

library:
  source-dirs: src

executables:
  shah-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - shah

tests:
  shah-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - shah
